
spring.datasource.url=jdbc:postgresql://localhost:5432/seguridad
spring.datasource.username=postgres
spring.datasource.password=0309

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081
